"""initial

Revision ID: 5339b55a51ad
Revises: 
Create Date: 2025-05-01 12:33:07.700349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5339b55a51ad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("video_ids", sa.JSON(), nullable=False),
        sa.Column("word_ids", sa.JSON(), nullable=False),
        sa.Column("vocabulary_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_model_id"), "user_model", ["id"], unique=False)
    op.create_table(
        "video_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ytb_id", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=250), nullable=False),
        sa.Column("video_path", sa.String(length=250), nullable=False),
        sa.Column("vtt_path", sa.String(length=250), nullable=False),
        sa.Column("zh_text", sa.String(length=1000000), nullable=True),
        sa.Column("en_text", sa.String(length=1000000), nullable=True),
        sa.Column("word_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
        sa.UniqueConstraint("ytb_id"),
    )
    op.create_index(op.f("ix_video_model_id"), "video_model", ["id"], unique=False)
    op.create_table(
        "families_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lemma", sa.String(length=50), nullable=False),
        sa.Column("word_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_families_user_id", "families_model", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_families_model_id"), "families_model", ["id"], unique=False
    )
    op.create_table(
        "graph_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_graph_model_id"), "graph_model", ["id"], unique=False)
    op.create_table(
        "sentence_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("line_ids", sa.JSON(), nullable=False),
        sa.Column("sentence_text", sa.String(length=50000), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sentence_video_language",
        "sentence_model",
        ["video_id", "language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sentence_model_id"), "sentence_model", ["id"], unique=False
    )
    op.create_table(
        "vocabulary_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "vocabulary", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_vocabulary_model_id"), "vocabulary_model", ["id"], unique=False
    )
    op.create_table(
        "graph_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("lemma", sa.String(length=50), nullable=False),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("word_ids", sa.JSON(), nullable=False),
        sa.Column("acquired", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graph_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("graph_id", "lemma", name="unique_lemma_per_graph"),
    )
    op.create_index(op.f("ix_graph_node_id"), "graph_node", ["id"], unique=False)
    op.create_index(op.f("ix_graph_node_lemma"), "graph_node", ["lemma"], unique=False)
    op.create_table(
        "line_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("original_line_number", sa.Integer(), nullable=False),
        sa.Column("line_text", sa.String(length=50000), nullable=False),
        sa.Column("start_timestamp", sa.String(length=100), nullable=False),
        sa.Column("end_timestamp", sa.String(length=100), nullable=False),
        sa.Column("sentence_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sentence_id"],
            ["sentence_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_line_language", "line_model", ["language"], unique=False)
    op.create_index(op.f("ix_line_model_id"), "line_model", ["id"], unique=False)
    op.create_table(
        "gap_filling_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("correct_answer_lemma", sa.String(length=50), nullable=False),
        sa.Column("select_list", sa.JSON(), nullable=False),
        sa.Column("distractors", sa.JSON(), nullable=False),
        sa.Column("correct_or_not", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["graph_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gap_filling_model_id"), "gap_filling_model", ["id"], unique=False
    )
    op.create_table(
        "graph_edge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("node1_id", sa.Integer(), nullable=False),
        sa.Column("node2_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graph_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node1_id"],
            ["graph_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node2_id"],
            ["graph_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_edge_id"), "graph_edge", ["id"], unique=False)
    op.create_table(
        "word_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("word", sa.String(length=50), nullable=False),
        sa.Column("lemma", sa.String(length=50), nullable=False),
        sa.Column("pos", sa.String(length=15), nullable=False),
        sa.Column("cefr", sa.String(length=10), nullable=True),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("translation", sa.String(length=50), nullable=True),
        sa.Column("vector", sa.JSON(), nullable=True),
        sa.Column("complexity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_word_language_word", "word_model", ["language", "word"], unique=False
    )
    op.create_index(op.f("ix_word_model_id"), "word_model", ["id"], unique=False)
    op.create_table(
        "chosen_words_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("lemma", sa.String(length=50), nullable=False),
        sa.Column("sentence", sa.String(length=500), nullable=False),
        sa.Column("translation", sa.String(length=50), nullable=True),
        sa.Column("marked_as_learned", sa.Boolean(), nullable=True),
        sa.Column("graph_node_id", sa.Integer(), nullable=True),
        sa.Column("record_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_node_id"],
            ["graph_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lemma"),
    )
    op.create_index(
        op.f("ix_chosen_words_model_id"), "chosen_words_model", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chosen_words_model_id"), table_name="chosen_words_model")
    op.drop_table("chosen_words_model")
    op.drop_index(op.f("ix_word_model_id"), table_name="word_model")
    op.drop_index("idx_word_language_word", table_name="word_model")
    op.drop_table("word_model")
    op.drop_index(op.f("ix_graph_edge_id"), table_name="graph_edge")
    op.drop_table("graph_edge")
    op.drop_index(op.f("ix_gap_filling_model_id"), table_name="gap_filling_model")
    op.drop_table("gap_filling_model")
    op.drop_index(op.f("ix_line_model_id"), table_name="line_model")
    op.drop_index("idx_line_language", table_name="line_model")
    op.drop_table("line_model")
    op.drop_index(op.f("ix_graph_node_lemma"), table_name="graph_node")
    op.drop_index(op.f("ix_graph_node_id"), table_name="graph_node")
    op.drop_table("graph_node")
    op.drop_index(op.f("ix_vocabulary_model_id"), table_name="vocabulary_model")
    op.drop_table("vocabulary_model")
    op.drop_index(op.f("ix_sentence_model_id"), table_name="sentence_model")
    op.drop_index("idx_sentence_video_language", table_name="sentence_model")
    op.drop_table("sentence_model")
    op.drop_index(op.f("ix_graph_model_id"), table_name="graph_model")
    op.drop_table("graph_model")
    op.drop_index(op.f("ix_families_model_id"), table_name="families_model")
    op.drop_index("idx_families_user_id", table_name="families_model")
    op.drop_table("families_model")
    op.drop_index(op.f("ix_video_model_id"), table_name="video_model")
    op.drop_table("video_model")
    op.drop_index(op.f("ix_user_model_id"), table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###
